name: Generate GitHub Trophy

on:
  schedule:
    - cron: "0 1 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Trophy
        uses: Erik-Donath/github-profile-trophy@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: githdavro
          file: images/trophy.svg
          theme: tokyo-night
          max-cols: 6
          max-rows: 2
          margin-width: 8
          margin-height: 8
          no-background: true
          no-frame: true

      - name: Commit Trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add images/trophy.svg

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update github trophy"
            git push
          fi
